apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-tkrbcajv
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/backend-tests-go-tkrbcajv:e381b5d5d25d7ad93ac768bcca523ef97d3955cd@sha256:ecbe716eacdf2a46521b7383a109663e0df2385da297b24799d6167988aeed18
        name: container-image  
